microsoft/vscode-markdown-languageservice

.vscode/settings.json
src/workspace.ts

Also notes that main is now protected

Fix windows CI

---

package-lock.json
package.json
src/languageFeatures/diagnostics.ts

Clear watchers when file is closed

---

README.md
package-lock.json
package.json
src/index.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts
src/util/editBuilder.ts

Add experimental support for update links on file rename

---

.eslintrc.js
.vscode/settings.json
src/config.ts
src/index.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/rename.ts
src/test/diagnostic.test.ts
src/test/fileRename.test.ts
src/test/inMemoryWorkspace.ts
src/test/pathCompletion.test.ts
src/test/rename.test.ts
src/util/path.ts

Allows generating edits when an entire directory is renamed

Enable directory rename edits

---

CHANGELOG.md
README.md
package.json

Just tagging the 0.0.0 release

0.0.0 Release

---

src/index.ts
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/documentSymbols.ts
src/languageFeatures/folding.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/languageFeatures/smartSelect.ts
src/test/rename.test.ts

Also fixes some logging calls to also log version

Trigger rename after link definition extract

---

src/languageFeatures/documentLinks.ts
src/languageFeatures/rename.ts
src/util/uri.ts

Fixes https://github.com/microsoft/vscode/issues/156859

Fix extra encoding of uris with percents in them

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts

- Bump version
- Adds `resolveLinkTarget` to resolve links

0.1.0 Alpha 2

---

src/index.ts
src/languageFeatures/rename.ts

Fixes https://github.com/microsoft/vscode/issues/148149

Add `RenameNotSupportedAtLocationError`

---

.vscode/launch.json
README.md
package.json
src/index.ts
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/codeActions/util.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/test/codeActions/extractLinkDef.test.ts
src/test/codeActions/removeLinkDefinition.test.ts
src/test/diagnostic.test.ts
src/test/util.ts

Add diagnostics for unused and duplicated link definitions

---

src/index.ts
src/languageFeatures/documentHighlights.ts
src/test/documentHighlights.test.ts

Add document highlighting support

---

src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Fixes https://github.com/microsoft/vscode/issues/162691

Fix links ending with `:`

---

CHANGELOG.md
package-lock.json
package.json

0.2.0-alpha 1

---

CHANGELOG.md
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/pathCompletions.ts
src/test/diagnostic.test.ts
src/test/documentLinks.test.ts

- Fix finding reference link shorthand with spaces in the name
- Fix references not being checked case insensitively
- Fix document links not picking first reference link in document

Fix some reference links issues

---

src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Fix inline code span ranges

---

CHANGELOG.md
package.json

Version bump for latest changes

0.2.0-alpha.2

---

CHANGELOG.md
package.json
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/documentLinks.ts
src/test/codeActions/extractLinkDef.test.ts
src/test/codeActions/removeLinkDefinition.test.ts
src/test/documentLinks.test.ts
src/types/position.ts

- Fix detection of reference links with images.
- Extract link definition should prefer inner links if on nested links.
- Remove unused link definition now deletes entire line instead of leaving blank line.

0.2-alpha 3

---

CHANGELOG.md
src/languageFeatures/rename.ts
src/test/fileRename.test.ts

Fixes https://github.com/microsoft/vscode/issues/164568

Don't add extra ./ on file rename

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/fileRename.ts
src/test/fileRename.test.ts

Fixes https://github.com/microsoft/vscode/issues/164643
Fixes https://github.com/microsoft/vscode/issues/164644

More edge cases around file renaming

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts

This fixes some cases around moving of one dir into another

Fix more edge cases around dir renames / moves

---

CHANGELOG.md
package-lock.json
package.json

0.2.0-alpha.8

---

CHANGELOG.md
src/languageFeatures/workspaceSymbols.ts
src/test/workspaceSymbol.test.ts

Workspace symbol search should be case insensitive

---

CHANGELOG.md
package-lock.json
package.json

Version 0.3.0-alpha.1

---

CHANGELOG.md
package.json

 0.3.0-alpha.3

---

src/test/pathCompletion.test.ts

Adds an additional test for path completions with angle bracket paths

Add extra test for workspace path completions

---

src/languageFeatures/fileRename.ts
src/languageFeatures/pathCompletions.ts

Adds details to path completion items

Add label details

---

src/languageFeatures/folding.ts

- Parse region markers once
- Use iterables more
- Use `function` more
- Avoid extra slice

Clean up folding code

---

CHANGELOG.md
src/languageFeatures/folding.ts
src/test/folding.test.ts

Add folding of tables and block quotes

---

src/languageFeatures/smartSelect.ts
src/test/smartSelect.test.ts

Adds tests for smart select of block quote and table and cleans up code

Add smart select tests and clean up code

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/documentSymbols.ts
src/languageFeatures/folding.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/languageFeatures/smartSelect.ts
src/logging.ts
src/tableOfContents.ts
src/test/codeActions/removeLinkDefinition.test.ts
src/test/diagnostic.test.ts
src/test/nulLogging.ts

Fixes https://github.com/microsoft/vscode-markdown-languageservice/issues/112
Cleans up the logging API and makes logging more consistent

Improve logging API and logging

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/pathCompletions.ts
src/test/documentLinks.test.ts
src/test/references.test.ts
src/test/rename.test.ts

Finding links in html elements inside markdown

---

CHANGELOG.md
package.json
src/languageFeatures/documentLinks.ts
src/languageFeatures/pathCompletions.ts
src/test/diagnostic.test.ts
src/test/documentLinks.test.ts
src/test/pathCompletion.test.ts

- Adding path completions in html attributes
- Fixes #131

0.4.0-alpha 2

---

CHANGELOG.md
package.json
src/languageFeatures/documentLinks.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts
src/test/rename.test.ts

0.4.0-alpha.3

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Fix detection of escaped angle bracket links

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts
src/test/rename.test.ts

- Use latest TS for building
- Fixes https://github.com/microsoft/vscode-markdown-languageservice/issues/139
- Fixes https://github.com/microsoft/vscode-markdown-languageservice/issues/140

0.4.0-alpha.5

---

src/languageFeatures/documentLinks.ts
src/test/diagnostic.test.ts

Also treat `+` as start of markdown list

---

src/languageFeatures/documentLinks.ts

Extract some duplicated code into a new class

Add InlineRanges helper class

---

src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/documentLinks.ts
src/test/codeActions/extractLinkDef.test.ts
src/test/documentHighlights.test.ts
src/test/rename.test.ts

Fix extract link def for auto-links

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/documentLinks.ts
src/types/range.ts

Also bumps some package versions and makes a few small code fixes, mostly working around https://github.com/microsoft/TypeScript/issues/56292

0.5.0-alpha.1

---

CHANGELOG.md
src/config.ts
src/languageFeatures/pathCompletions.ts
src/util/mdBuilder.ts
src/util/media.ts

Fixes https://github.com/microsoft/vscode/issues/209561

Add links and image preview for path completions

---

CHANGELOG.md
README.md
package.json
src/languageFeatures/pathCompletions.ts

Also adds previews for videos to match our hover support

0.5.0-alpha.5

---

src/languageFeatures/documentSymbols.ts
src/test/documentSymbols.test.ts

Use loop instead of recursion

---

CHANGELOG.md
package-lock.json
package.json
src/tableOfContents.ts
src/test/documentSymbols.test.ts
src/test/workspaceSymbol.test.ts

Don't include markup in header symbol text

---

package-lock.json
package.json

Also makes sure we pull in the latest node 20 typings

Bump TS version

---

CHANGELOG.md
src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts
src/test/fileRename.test.ts

Fix detection and renaming for common multi-line links

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/smartSelect.ts
src/test/smartSelect.test.ts

Fixes smart select of auto links  and preps for publishing 0.5.0-alpha.10

0.5.0-alpha.10

---

CHANGELOG.md
src/languageFeatures/pathCompletions.ts
src/test/pathCompletion.test.ts

For https://github.com/microsoft/vscode/issues/248467

Fix completions of unicode headers when you've already typed part of the header

---

src/languageFeatures/documentLinks.ts
src/languageFeatures/pathCompletions.ts
src/test/documentLinks.test.ts
src/test/pathCompletion.test.ts

Fix reference/definition completions for non word ref names

---

src/languageFeatures/smartSelect.ts
src/test/smartSelect.test.ts

Fix smart selection for image link cases
