microsoft/vscode-markdown-languageservice

src/index.ts
src/languageFeatures/definitions.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/references.ts
src/test/definition.test.ts
src/test/fileReferences.test.ts
src/test/references.test.ts
src/test/rename.test.ts

This rewrites `go to def` to not use `find all references`. Doing so is slow on large workspaces as it needs to scan through every file in the workspace. We don't need to do that when looking up a definition
From https://github.com/microsoft/vscode/issues/152494

Improve performance for `go to def`

---

src/config.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts

Updates rename file to try preserving the file extension
Also:
- Adds a test for rename file where file has spaces in the name
- Make `rename` use the language configuration to get the default markdown file extension instead of hardcoding `.md`

Make rename file preserve the file extension

---

src/languageFeatures/rename.ts
src/test/fileRename.test.ts
src/test/rename.test.ts
src/util/editBuilder.ts

Looks like workspace edits need to use either `changes` or `documentChanges`. If you use both, the `changes` are silently dropped
Also removes `MdWorkspaceEdit` since it is no longer needed in lsp world

Fix workspace edit using both changes and documentChanges

---

src/languageFeatures/documentLinks.ts

Something seems to have changed in the latest VS Code where `undefined` no longer defaults to active group

Always use active group for doc links

---

README.md
example.cjs
src/index.ts
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/documentSymbols.ts
src/languageFeatures/organizeLinkDefs.ts
src/languageFeatures/workspaceSymbols.ts
src/test/diagnostic.test.ts
src/test/documentSymbols.test.ts
src/test/extractLinkDef.test.ts
src/test/inMemoryDocument.ts
src/test/organizeLinkDef.test.ts
src/test/util.ts
src/test/workspaceSymbol.test.ts
src/types/range.ts
src/util/editBuilder.ts

Combination of a few different commits about link definitions that I added while on recent plane rides :)
- Add option to include link definitions in the document outline. Controlled by a new `includeLinkDefinitions` param
- Adds an organize link definition action. This groups all link definitions to the bottom of the file and sorts them Fixes #25
- Adds a code action for extracting a link to a definition Fixes #24

Adding more tooling for working with link definitions

---

src/test/workspaceCache.test.ts
src/workspaceCache.ts

The workspace cache needs to have listeners hooked up early if any calls are made to `getForDocs`

Fix workspace caching for rename

---

src/languageFeatures/documentLinks.ts

Also:
- moves a type closer to its usage
- Remove explicit enum values

Use better names for functions

---

src/languageFeatures/documentLinks.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/rename.ts
src/tableOfContents.ts
src/test/documentLinks.test.ts

Fixes #2
Switches the doc link provider to use normal uris in most cases
In cases where we need to use `vscode.open`, we instead use a new proxy command that clients must register (this command should forward to `vscode.open`)
This is done as it forces `vscode.open` to be executed on the exthost side instead of in core

Fix notebook document links

---

CHANGELOG.md
package.json
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

- Using `editor.action.rename` directly causes VS Code to evaluate the command without converting the types properly. Instead we need to use a proxy command to handle this
- Also fixes detection of image reference links when the text is empty. This type of link is not normally valid but is supported for images

Fix image reference links and use custom command for rename

---

CHANGELOG.md
package.json
src/languageFeatures/diagnostics.ts
src/test/diagnostic.test.ts

This fixes a tricky diagnostics case where we were incorrectly marking a document as not existing because it was the document that triggered the diagnostics request

Fix false positive diagnostic with files that link to themselves

---

CHANGELOG.md
package-lock.json
package.json
src/languageFeatures/diagnostics.ts

This adds a new `disposeDocumentResources` method for the diagnostics manager to clean up watchers when a document is closed by the editor

Add disposeDocumentResources method

---

CHANGELOG.md
package-lock.json
package.json
src/parser.ts
src/slugify.ts
src/tableOfContents.ts
src/test/references.test.ts
src/test/tableOfContents.test.ts

Fixes #48
Updates our slugifier to allow underscores
Also switches to use the parsed markdown to generate the header slug instead of using the source text

Allow underscores in headers

---

src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/test/diagnostic.test.ts

Stops us from trying to check if there is a heading `#L123` for links such as `[text](#L123)` which are links to line numbers

Don't validate line number links

---

src/languageFeatures/documentLinks.ts

We need to pass in the uri, not the full link object

Fix links to folders

---

src/languageFeatures/diagnostics.ts
src/languageFeatures/documentHighlights.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/workspaceSymbols.ts
src/tableOfContents.ts
src/test/tableOfContents.test.ts
src/test/workspaceCache.test.ts
src/workspaceCache.ts

This makes the workspace cache able to cancel its computations when the file we are asking about is deleted. This is important as trying to compute values for deleted files will often throw exceptions
This also makes us observe the cancellation token in more spots

Make sure we cancel computations in more cases

---

src/languageFeatures/fileRename.ts
src/test/fileRename.test.ts

We never need to touch links such as `[text](#header)` when moving around files

Fix incorrect renames of headers

---

.eslintrc.js
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/definitions.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentHighlights.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/documentSymbols.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/folding.ts
src/languageFeatures/organizeLinkDefs.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/languageFeatures/smartSelect.ts
src/languageFeatures/workspaceSymbols.ts
src/tableOfContents.ts
src/test/inMemoryWorkspace.ts
src/util/cancellation.ts
src/util/dispose.ts
src/util/editBuilder.ts
src/util/limiter.ts
src/util/resourceMap.ts
src/workspaceCache.ts

Require `_` on privates and forbid it on publics

Adopt basic naming rules

---

CHANGELOG.md
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/tableOfContents.ts
src/test/inMemoryDocument.ts
src/test/inMemoryWorkspace.ts
src/types/textDocument.ts
src/workspaceCache.ts

This helps reduce calls to `URI.parse`

Add optional $uri to get the actual uri of a document

---

.eslintrc.js
package.json
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/definitions.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentHighlights.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/documentSymbols.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/folding.ts
src/languageFeatures/organizeLinkDefs.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/languageFeatures/smartSelect.ts
src/languageFeatures/workspaceSymbols.ts
src/tableOfContents.ts
src/test/inMemoryDocument.ts
src/test/inMemoryWorkspace.ts
src/util/cancellation.ts
src/util/dispose.ts
src/util/editBuilder.ts
src/util/lazy.ts
src/util/limiter.ts
src/util/resourceMap.ts
src/workspaceCache.ts
tsconfig.base.json

This switches us to use runtime privates instead of the `private` keyword. The main benefit is that lets us easily mangle private names

Use ES # privates instead of private keyword

---

CHANGELOG.md
package-lock.json
package.json

Bumping version to use `@vscode/l10n`

0.3.0-alpha.2

---

build/pipeline.yml

Explicitly run `api-extractor` as part of pre-publish step

---

api-extractor.json
package-lock.json
package.json

API extract does not auto create the directories it needs. This causes our release pipeline to fail
Also fixes api extractor running using the wrong tsconfig, which was generating a lot of warnings

Make sure api-extractor output dir exists

---

.eslintrc.js
.vscode/settings.json

- Disables linting of the generated `d.ts` file when opened in an editor
- Makes VS Code treat api-extractor json files as `jsonc`

Fix linting of generated d.ts and json files

---

CHANGELOG.md
package-lock.json
package.json
src/index.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/rename.ts
src/languageFeatures/workspaceSymbols.ts
src/test/pathCompletion.test.ts

Fixes #110
Lets you type `[text](##` to see suggestions for every header in current workspace. Accepting one of these suggestions inserts a link to it

Add support for cross workspace header completions

---

CHANGELOG.md
src/config.ts
src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/codeActions/removeLinkDefinition.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/rename.ts
src/test/fileRename.test.ts
src/test/pathCompletion.test.ts
src/util/editBuilder.ts
src/util/file.ts
src/util/path.ts

Controls if completions to markdown files should include or drop the file extension (`.md`)

Add preferredMdPathExtensionStyle setting

---

src/config.ts
src/index.ts
src/languageFeatures/pathCompletions.ts
src/test/fileRename.test.ts
src/test/pathCompletion.test.ts

Adds setting to include workspace header completions when you type a single `#` instead of requiring `##`
This also converts an existing setting to use an enum for better documentation.

Add allow returning workspace header completions on single `#`

---

src/index.ts
src/languageFeatures/pathCompletions.ts
src/test/pathCompletion.test.ts

We accept additional options so we need to use the right type here

Fix type on `getCompletionItems`

---

CHANGELOG.md
package-lock.json
package.json
src/config.ts

Switches to use a Proxy instead of a spread so that getters are properly preserved
Also bumps version so we can release this change

Allow language service configuration to be changed dynamically

---

CHANGELOG.md
src/languageFeatures/pathCompletions.ts
src/languageFeatures/rename.ts
src/test/pathCompletion.test.ts
src/util/mdLinks.ts
tsconfig.base.json

Fixes #17
With this change, we no longer call `encodeURI` for path completions. This usually was not needed. We then also better handle cases where paths have characters with special meanings

Fix some edge cases around path completions

---

CHANGELOG.md
package.json
src/languageFeatures/pathCompletions.ts
src/test/diagnostic.test.ts
src/test/pathCompletion.test.ts

Fix path completions for file names with `%`

---

src/languageFeatures/documentLinks.ts
src/test/diagnostic.test.ts
src/test/documentLinks.test.ts

Should now handle:
- `[[text]]` (this should treat `text` as the reference link)
- Reference contains escaped brackets

Fix link detection for few more reference link cases

---

src/languageFeatures/documentLinks.ts
src/test/diagnostic.test.ts
src/test/documentLinks.test.ts

Fixes #153
Now that negative lookaheads are supported in all envs, we can use them in this regexp

Fix inline code regexp

---

src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

https://github.com/microsoft/vscode/issues/195756
https://github.com/microsoft/vscode/issues/195487
Also switches us to use named capture groups for readability

Fix catastrophic backtracking for link shorthand

---

CHANGELOG.md
src/languageFeatures/workspaceSymbols.ts
src/test/workspaceSymbol.test.ts
src/util/string.ts

Loosens up matching so we only require the query characters to appear in order instead of as a substring

Use fuzzy matching for workspace symbol search

---

CHANGELOG.md
src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Fixes #15
Fixes a few more cases where escaped links were being recognized. Possible now that we can use negative lookbehind

Don't recognized escaped links

---

src/languageFeatures/codeActions/extractLinkDef.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentHighlights.ts
src/languageFeatures/fileRename.ts
src/languageFeatures/pathCompletions.ts
src/languageFeatures/references.ts
src/languageFeatures/updatePastedLinks.ts
src/test/updatePastedLinks.test.ts
src/util/path.ts

Using `.toString` was unsafe as it hide some typing errors. This PR adds a new `isSameResource` helper which catches these

Fix URI equality checks

---

CHANGELOG.md
package.json
src/languageFeatures/rename.ts
src/languageFeatures/updatePastedLinks.ts
src/types/inMemoryDocument.ts

This helps clients that try to cache parsing of md docs

Identify temp versions of documents

---

src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Fix bad multiline matches for link definitions

---

CHANGELOG.md
src/languageFeatures/definitions.ts
src/languageFeatures/diagnostics.ts
src/languageFeatures/documentHighlights.ts
src/languageFeatures/documentLinks.ts
src/languageFeatures/references.ts
src/tableOfContents.ts
src/test/diagnostic.test.ts
src/test/documentLinks.test.ts
src/test/tableOfContents.test.ts

Fixes https://github.com/microsoft/vscode/issues/228085

Support spaces in angle bracket link fragments

---

src/languageFeatures/documentLinks.ts
src/test/documentLinks.test.ts

Allow [common alert syntax](https://learn.microsoft.com/en-us/contribute/content/markdown-reference#alerts-note-tip-important-caution-warning) used in Microsoft Learn and on [GitHub](https://github.com/orgs/community/discussions/16925) without raising `link.no-such-reference`. Fixing #164

#164 Allow common [!ANY] alerts
